const VERSION='3.0.0', STORE='vowloData';
const clone=x=>JSON.parse(JSON.stringify(x));
const defaults={version:3,setup:{names:'Emma & James',date:'2027-06-12',budget:25000,currency:'USD',venue:'',guestLimit:120},tasks:[{name:'Book venue',category:'Planning',owner:'Both',due:'',status:'To do',done:false},{name:'Book photographer',category:'Vendors',owner:'Both',due:'',status:'To do',done:false},{name:'Draft guest list',category:'Guests',owner:'Both',due:'',status:'Done',done:true},{name:'Choose wedding style',category:'Design',owner:'Both',due:'',status:'Done',done:true}],guests:[{name:'Olivia Martin',household:'Martin',email:'',phone:'',invite:'Sent',rsvp:'Yes',meal:'',dietary:'',table:'',gift:'',notes:''},{name:'Noah Martin',household:'Martin',email:'',phone:'',invite:'Sent',rsvp:'Awaiting',meal:'',dietary:'',table:'',gift:'',notes:''}],expenses:[{item:'Venue',category:'Venue',estimate:6500,final:6500,paid:3000},{item:'Photography',category:'Photo',estimate:2800,final:2800,paid:1000}],vendors:[],timeline:[],tables:[{name:'Table 1',capacity:8,notes:''}],gifts:[],venues:[],photos:[],music:[],honeymoon:[],emergency:[],inspiration:[],contacts:[]};
let page='home', data=migrate(load());
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||clone(defaults)}catch{return clone(defaults)}}
function migrate(d){d=d||clone(defaults);d.setup={...defaults.setup,...(d.setup||{})};if((d.tasks||[])[0] instanceof Array)d.tasks=d.tasks.map(x=>({name:x[0],category:x[1]||'Planning',owner:'Both',due:'',status:x[2]?'Done':'To do',done:!!x[2]}));if((d.guests||[])[0] instanceof Array)d.guests=d.guests.map(x=>({name:x[0],household:'',email:'',phone:'',invite:'Not sent',rsvp:x[1]||'Awaiting',meal:'',dietary:'',table:'',gift:'',notes:''}));if((d.expenses||[])[0] instanceof Array)d.expenses=d.expenses.map(x=>({item:x[0],category:'Other',estimate:+x[1]||0,final:+x[1]||0,paid:0}));['tasks','guests','expenses','vendors','timeline','tables','gifts','venues','photos','music','honeymoon','emergency','inspiration','contacts'].forEach(k=>d[k]=Array.isArray(d[k])?d[k]:[]);if(!d.tables.length)d.tables=clone(defaults.tables);d.version=3;localStorage.setItem(STORE,JSON.stringify(d));return d}
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(msg='Saved'){localStorage.setItem(STORE,JSON.stringify(data));toast(msg)}
function money(n){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:(data.setup.currency||'USD').toUpperCase(),maximumFractionDigits:0}).format(+n||0)}catch{return `${+n||0} ${esc(data.setup.currency||'USD')}`}}
function days(){if(!data.setup.date)return null;let d=new Date(data.setup.date+'T12:00:00'),n=new Date();return Math.ceil((d-n)/86400000)}
function pct(){return data.tasks.length?Math.round(data.tasks.filter(x=>x.done).length/data.tasks.length*100):0}
function spent(){return data.expenses.reduce((a,x)=>a+(+x.final||+x.estimate||0),0)}function paid(){return data.expenses.reduce((a,x)=>a+(+x.paid||0),0)}
function nav(){return `<nav class="tabs" aria-label="Primary"><div>${[['home','⌂','Home'],['plan','✓','Plan'],['guests','♙','Guests'],['budget','$','Budget'],['more','•••','More']].map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div></nav>`}
function header(title,sub=''){return `<header class="top"><div class="brand">VOWLO</div><h1>${title}</h1>${sub?`<div class="sub">${sub}</div>`:''}</header>`}
function home(){let yes=data.guests.filter(x=>x.rsvp==='Yes').length,d=days(),left=(+data.setup.budget||0)-spent(),up=data.tasks.filter(x=>!x.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,3);return `${header(`Hello, ${esc(data.setup.names||'lovebirds')} ♡`,'Everything for your day, in one calm place.')}<section class="hero"><div class="sub">YOUR WEDDING</div><div class="count">${d===null?'Set your date':d<0?'Just married ♡':d+' days'}</div><div>${data.setup.date?new Date(data.setup.date+'T12:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'}):'Add your wedding date in Setup'}</div><div class="progress"><i style="width:${pct()}%"></i></div><small>${pct()}% of planning tasks complete</small></section><div class="grid"><div class="card metric"><span class="sub">Budget left</span><b>${money(left)}</b></div><div class="card metric"><span class="sub">Guests confirmed</span><b>${yes}/${data.guests.length}</b></div></div><div class="quick"><button onclick="go('plan');setTimeout(()=>$('#taskName')?.focus(),20)"><span>＋</span>Task</button><button onclick="go('guests');setTimeout(()=>$('#guestName')?.focus(),20)"><span>＋</span>Guest</button><button onclick="go('budget');setTimeout(()=>$('#expenseItem')?.focus(),20)"><span>＋</span>Expense</button></div><div class="sectionTitle"><h2>Up next</h2><button class="btn soft small" onclick="go('plan')">View all</button></div><div class="list">${up.map(x=>taskRow(x,data.tasks.indexOf(x))).join('')||'<div class="empty">You’re all caught up ✨</div>'}</div>`}
function taskRow(x,i){let overdue=x.due&&!x.done&&new Date(x.due+'T23:59')<new Date();return `<div class="row"><input class="check" aria-label="Complete task" type="checkbox" ${x.done?'checked':''} onchange="toggleTask(${i})"><div class="grow"><b style="${x.done?'text-decoration:line-through;opacity:.55':''}">${esc(x.name)}</b><small class="${overdue?'overdue':''}">${esc(x.category)}${x.owner?' • '+esc(x.owner):''}${x.due?' • '+esc(x.due):''}</small></div><span class="pill ${x.done?'done':overdue?'warn':''}">${x.done?'Done':overdue?'Overdue':'To do'}</span><button class="btn ghost small" aria-label="Delete" onclick="removeItem('tasks',${i})">×</button></div>`}
function plan(){return `${header('Planning checklist','Tasks, owners and dates — all in one place.')}<div class="card"><div class="form2"><div class="field"><label>TASK</label><input id="taskName" placeholder="e.g. Book florist"></div><div class="field"><label>CATEGORY</label><select id="taskCat"><option>Planning</option><option>Vendors</option><option>Guests</option><option>Design</option><option>Wedding day</option></select></div><div class="field"><label>OWNER</label><input id="taskOwner" placeholder="Both / name"></div><div class="field"><label>DUE DATE</label><input id="taskDue" type="date"></div></div><button class="btn" onclick="addTask()">Add task</button></div><div class="sectionTitle"><h2>${pct()}% complete</h2><span class="sub">${data.tasks.filter(x=>x.done).length}/${data.tasks.length}</span></div><div class="list">${data.tasks.map(taskRow).join('')||'<div class="empty">Add your first planning task.</div>'}</div>`}
function guestRow(x,i){return `<div class="row"><div class="grow"><b>${esc(x.name)}</b><small>${esc(x.household||'No household')}${x.meal?' • '+esc(x.meal):''}${x.table?' • '+esc(x.table):''}${x.dietary?' • ⚑ '+esc(x.dietary):''}</small></div><select aria-label="RSVP" onchange="data.guests[${i}].rsvp=this.value;save();render()"><option ${x.rsvp==='Awaiting'?'selected':''}>Awaiting</option><option ${x.rsvp==='Yes'?'selected':''}>Yes</option><option ${x.rsvp==='No'?'selected':''}>No</option></select><button class="btn ghost small" onclick="removeItem('guests',${i})">×</button></div>`}
function guests(){let q=(window.guestQuery||'').toLowerCase(),arr=data.guests.map((x,i)=>[x,i]).filter(([x])=>!q||JSON.stringify(x).toLowerCase().includes(q));let y=data.guests.filter(x=>x.rsvp==='Yes').length,n=data.guests.filter(x=>x.rsvp==='No').length;return `${header('Guests & RSVP','Track invitations, meals, dietary needs and seating.')}<div class="grid3"><div class="card metric"><span class="sub">Yes</span><b>${y}</b></div><div class="card metric"><span class="sub">Awaiting</span><b>${data.guests.length-y-n}</b></div><div class="card metric"><span class="sub">No</span><b>${n}</b></div></div><div class="card"><div class="form2"><div class="field"><label>GUEST NAME</label><input id="guestName" placeholder="Full name"></div><div class="field"><label>HOUSEHOLD</label><input id="guestHouse" placeholder="Family / party"></div><div class="field"><label>RSVP</label><select id="guestRsvp"><option>Awaiting</option><option>Yes</option><option>No</option></select></div><div class="field"><label>MEAL</label><input id="guestMeal" placeholder="Meal choice"></div><div class="field"><label>DIETARY / ACCESS</label><input id="guestDiet" placeholder="Allergies, access needs"></div><div class="field"><label>TABLE</label><select id="guestTable"><option value="">Unassigned</option>${data.tables.map(t=>`<option>${esc(t.name)}</option>`).join('')}</select></div></div><button class="btn" onclick="addGuest()">Add guest</button></div><div class="sectionTitle"><h2>Guest list</h2><span class="sub">${data.guests.length} people</span></div><input class="search" placeholder="Search guests…" value="${esc(window.guestQuery||'')}" oninput="window.guestQuery=this.value;render()"><div class="list" style="margin-top:9px">${arr.map(([x,i])=>guestRow(x,i)).join('')||'<div class="empty">No matching guests.</div>'}</div>`}
function budget(){let total=+data.setup.budget||0,balance=spent()-paid();return `${header('Budget','Track estimates, final costs and payments.')}<div class="grid"><div class="card metric"><span class="sub">Budget</span><b>${money(total)}</b></div><div class="card metric"><span class="sub">Forecast</span><b>${money(spent())}</b></div><div class="card metric"><span class="sub">Paid</span><b>${money(paid())}</b></div><div class="card metric"><span class="sub">Still due</span><b>${money(balance)}</b></div></div>${spent()>total&&total?'<div class="notice overdue">Forecast is above your current budget by '+money(spent()-total)+'.</div>':''}<div class="card"><div class="form2"><div class="field"><label>ITEM</label><input id="expenseItem" placeholder="e.g. Flowers"></div><div class="field"><label>CATEGORY</label><input id="expenseCat" placeholder="e.g. Florals"></div><div class="field"><label>ESTIMATE</label><input id="expenseEst" type="number" inputmode="decimal" placeholder="0"></div><div class="field"><label>FINAL COST</label><input id="expenseFinal" type="number" inputmode="decimal" placeholder="0"></div><div class="field"><label>PAID</label><input id="expensePaid" type="number" inputmode="decimal" placeholder="0"></div></div><button class="btn" onclick="addExpense()">Add budget item</button></div><div class="sectionTitle"><h2>Budget items</h2><span class="sub">${money(total-spent())} left</span></div><div class="list">${data.expenses.map((x,i)=>`<div class="row"><div class="grow"><b>${esc(x.item)}</b><small>${esc(x.category||'Other')} • paid ${money(x.paid||0)}</small></div><b>${money(x.final||x.estimate)}</b><button class="btn ghost small" onclick="removeItem('expenses',${i})">×</button></div>`).join('')||'<div class="empty">Add your first budget item.</div>'}</div>`}
const tools=[['setup','⚙ Setup','Wedding details'],['vendors','♧ Vendors','Contacts & bookings'],['timeline','◷ Wedding day','Run of show'],['seating','◉ Seating','Tables & assignments'],['venues','⌂ Venues','Compare options'],['photos','□ Photos','Must-have shots'],['music','♫ Music','Songs & moments'],['honeymoon','✈ Honeymoon','Travel planning'],['emergency','＋ Emergency kit','Packing list'],['gifts','♡ Gifts','Thank-you tracking'],['inspiration','✦ Inspiration','Ideas & decisions'],['contacts','☎ Contacts','Key people']];
function more(){return `${header('More tools','Everything else, without cluttering your home screen.')}<div class="moregrid">${tools.map(x=>`<button class="card tool" onclick="go('${x[0]}')"><b>${x[1]}</b><small class="sub">${x[2]}</small></button>`).join('')}</div><div class="sectionTitle"><h2>Your data</h2></div><div class="card"><div class="toolbar"><button class="btn soft" onclick="exportData()">Export backup</button><button class="btn soft" onclick="$('#importFile').click()">Import backup</button><input id="importFile" type="file" accept="application/json" class="sr" onchange="importData(this)"></div><p class="sub">Vowlo saves automatically in this browser. Export a backup before clearing Safari data or changing devices.</p><button class="btn danger small" onclick="resetApp()">Reset all data</button></div><div class="notice"><b>Vowlo ${VERSION}</b> • Offline-ready after the first successful load. For a commercial multi-device product, cloud accounts and secure sync are still a separate production step.</div>`}
function setup(){return `${header('Wedding setup','Set the essentials once; change them anytime.')}<div class="card"><div class="field"><label>PARTNER NAMES</label><input id="sNames" value="${esc(data.setup.names)}"></div><div class="form2"><div class="field"><label>WEDDING DATE</label><input id="sDate" type="date" value="${esc(data.setup.date)}"></div><div class="field"><label>VENUE</label><input id="sVenue" value="${esc(data.setup.venue)}"></div><div class="field"><label>TOTAL BUDGET</label><input id="sBudget" type="number" value="${esc(data.setup.budget)}"></div><div class="field"><label>CURRENCY CODE</label><input id="sCurrency" maxlength="3" value="${esc(data.setup.currency)}"></div><div class="field"><label>GUEST LIMIT</label><input id="sLimit" type="number" value="${esc(data.setup.guestLimit)}"></div></div><button class="btn" onclick="saveSetup()">Save setup</button></div>`}
const schemas={vendors:{title:'Vendors',desc:'Contacts, bookings and arrival details.',fields:[['service','Service'],['business','Business'],['contact','Contact'],['phone','Phone'],['status','Status'],['arrival','Arrival / delivery']]},timeline:{title:'Wedding day',desc:'Build a clear run of show.',fields:[['time','Time'],['activity','Activity'],['location','Location'],['lead','Lead'],['contact','Contact']]},venues:{title:'Venue comparison',desc:'Compare your strongest options.',fields:[['name','Venue'],['location','Location'],['capacity','Capacity'],['cost','Estimated cost'],['rating','Rating / 5']]},photos:{title:'Photo shot list',desc:'Keep must-have moments visible.',fields:[['shot','Moment / shot'],['people','People'],['location','Location'],['priority','Priority']]},music:{title:'Music',desc:'Songs for the moments that matter.',fields:[['moment','Moment'],['song','Song'],['artist','Artist'],['confirmed','Confirmed?']]},honeymoon:{title:'Honeymoon',desc:'Travel plans and bookings.',fields:[['item','Item'],['place','Provider / place'],['start','Start'],['end','End'],['cost','Cost']]},emergency:{title:'Emergency kit',desc:'Small things that save the day.',fields:[['item','Item'],['category','Category'],['assigned','Assigned to'],['packed','Packed?']]},gifts:{title:'Gifts',desc:'Track gifts and thank-you notes.',fields:[['from','From'],['gift','Gift'],['received','Received'],['thanks','Thank-you sent?']]},inspiration:{title:'Inspiration',desc:'Capture ideas, then make decisions.',fields:[['category','Category'],['idea','Idea'],['style','Style / keywords'],['decision','Decision']]},contacts:{title:'Key contacts',desc:'The people your wedding party may need.',fields:[['role','Role / service'],['name','Name / business'],['phone','Phone'],['email','Email']]}};
function generic(key){let s=schemas[key],arr=data[key];return `${header(s.title,s.desc)}<div class="card"><div class="form2">${s.fields.map(([k,l],i)=>`<div class="field"><label>${l.toUpperCase()}</label><input id="f${i}" placeholder="${esc(l)}"></div>`).join('')}</div><button class="btn" onclick="addGeneric('${key}')">Add</button></div><div class="sectionTitle"><h2>${s.title}</h2><span class="sub">${arr.length} items</span></div><div class="list">${arr.map((x,i)=>`<div class="row"><div class="grow"><b>${esc(x[s.fields[0][0]])}</b><small>${s.fields.slice(1).map(([k])=>x[k]).filter(Boolean).map(esc).join(' • ')}</small></div><button class="btn ghost small" onclick="removeItem('${key}',${i})">×</button></div>`).join('')||'<div class="empty">Nothing here yet.</div>'}</div>`}
function seating(){let assigned=data.guests.filter(g=>g.table).length;return `${header('Seating','Create tables and assign confirmed guests.')}<div class="grid"><div class="card metric"><span class="sub">Tables</span><b>${data.tables.length}</b></div><div class="card metric"><span class="sub">Assigned</span><b>${assigned}</b></div></div><div class="card"><div class="form2"><div class="field"><label>TABLE NAME</label><input id="tableName" placeholder="e.g. Table 8"></div><div class="field"><label>CAPACITY</label><input id="tableCap" type="number" value="8"></div></div><button class="btn" onclick="addTable()">Add table</button></div><div class="sectionTitle"><h2>Tables</h2></div><div class="stack">${data.tables.map((t,i)=>{let gs=data.guests.filter(g=>g.table===t.name),over=gs.length>(+t.capacity||0);return `<div class="tableCard"><div class="tableHead"><div><b>${esc(t.name)}</b><small class="sub"> ${gs.length}/${+t.capacity||0} seats</small></div><button class="btn ghost small" onclick="removeTable(${i})">×</button></div><div class="seatlist">${gs.map(g=>`<span class="seat">${esc(g.name)}</span>`).join('')||'<span class="sub">No guests assigned</span>'}</div>${over?'<small class="overdue">Over capacity</small>':''}</div>`}).join('')}</div><div class="notice">Assign a table from each guest’s record in <b>Guests</b>. Confirmed guests are usually the best place to start.</div>`}
function render(){let body=page==='home'?home():page==='plan'?plan():page==='guests'?guests():page==='budget'?budget():page==='more'?more():page==='setup'?setup():page==='seating'?seating():schemas[page]?generic(page):home();$('#app').innerHTML=`<main class="shell">${body}</main>${nav()}<div class="toast" id="toast" role="status"></div>`}
function go(p){page=p;render();scrollTo(0,0)}function val(id){return $(id)?.value.trim()||''}
function addTask(){let name=val('#taskName');if(!name)return toast('Add a task name');data.tasks.push({name,category:val('#taskCat')||'Planning',owner:val('#taskOwner')||'Both',due:val('#taskDue'),status:'To do',done:false});save();render()}
function toggleTask(i){data.tasks[i].done=!data.tasks[i].done;data.tasks[i].status=data.tasks[i].done?'Done':'To do';save();render()}
function addGuest(){let name=val('#guestName');if(!name)return toast('Add a guest name');data.guests.push({name,household:val('#guestHouse'),email:'',phone:'',invite:'Not sent',rsvp:val('#guestRsvp')||'Awaiting',meal:val('#guestMeal'),dietary:val('#guestDiet'),table:val('#guestTable'),gift:'',notes:''});save();render()}
function addExpense(){let item=val('#expenseItem');if(!item)return toast('Add an item');data.expenses.push({item,category:val('#expenseCat')||'Other',estimate:+val('#expenseEst')||0,final:+val('#expenseFinal')||+val('#expenseEst')||0,paid:+val('#expensePaid')||0});save();render()}
function addGeneric(key){let s=schemas[key],o={};s.fields.forEach(([k],i)=>o[k]=val('#f'+i));if(!o[s.fields[0][0]])return toast('Add the first field');data[key].push(o);save();render()}
function addTable(){let name=val('#tableName'),capacity=+val('#tableCap')||0;if(!name)return toast('Add a table name');if(data.tables.some(t=>t.name.toLowerCase()===name.toLowerCase()))return toast('Table name already exists');data.tables.push({name,capacity,notes:''});save();render()}
function removeTable(i){let t=data.tables[i];if(data.guests.some(g=>g.table===t.name))return alert('Move guests off this table before deleting it.');if(confirm(`Delete ${t.name}?`)){data.tables.splice(i,1);save();render()}}
function removeItem(k,i){if(confirm('Delete this item?')){data[k].splice(i,1);save();render()}}
function saveSetup(){data.setup.names=val('#sNames');data.setup.date=val('#sDate');data.setup.venue=val('#sVenue');data.setup.budget=+val('#sBudget')||0;data.setup.currency=(val('#sCurrency')||'USD').toUpperCase();data.setup.guestLimit=+val('#sLimit')||0;save();go('home')}
function toast(t){let e=$('#toast');if(e){e.textContent=t;e.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>e.classList.remove('show'),1000)}}
function exportData(){let b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`vowlo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(input){let f=input.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let v=JSON.parse(r.result);if(!v.setup||!Array.isArray(v.tasks)||!Array.isArray(v.guests))throw Error();data=migrate(v);save('Backup imported');render();alert('Backup imported successfully.')}catch{alert('This does not look like a valid Vowlo backup.')}};r.readAsText(f)}
function resetApp(){if(confirm('Reset Vowlo and erase all planning data stored in this browser?')){data=clone(defaults);save('Reset complete');render()}}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=3.0.0').then(r=>r.update()).catch(()=>{}))}
render();
