/* Additive V4 UI: original V3 screens and five-tab navigation are retained. */
const oldMore=more, oldRender=render;
more=function(){return oldMore().replace('<div class="moregrid">','<div class="card"><h2>Your account</h2><p>Manage sign-in, sync and privacy.</p><button class="btn" onclick="go(\'account\')">Account & sync</button></div><div class="moregrid" style="margin-top:12px">').replace('Vowlo saves automatically in this browser. Export a backup before clearing Safari data or changing devices.','Device-only work stays in this browser. When signed in, check Account & sync for your cloud status. Export backups regularly.').replace('Reset all data','Delete planner data').replace('Offline-ready after the first successful load. For a commercial multi-device product, cloud accounts and secure sync are still a separate production step.','Release candidate. Cloud availability depends on configuration; see Account & sync.');};
function account(){
 const s=VowloCloud.status();
 return `${header('Account & sync','Your day. Your data. Your choice.')}<div class="card"><p id="accountStatus" role="status">${esc(s.message)}</p>${s.user?`<p>Signed in as <b>${esc(s.user.email)}</b></p><div class="toolbar"><button class="btn" onclick="VowloCloud.sync()">Sync now</button><button class="btn soft" onclick="accountAction('logout')">Sign out</button></div>${s.conflict?`<div class="notice"><h2>Two copies need your attention</h2><p>No copy has been overwritten. Export both before choosing which one to keep.</p><div class="toolbar"><button class="btn soft" onclick="exportData()">Export this copy</button><button class="btn soft" onclick="VowloCloud.exportRemote()">Export cloud copy</button><button class="btn" onclick="accountAction('remote')">Use cloud copy</button><button class="btn danger" onclick="accountAction('local')">Use this copy</button></div></div>`:''}${VowloCloud.hasLegacy()?`<div class="notice"><h2>Bring your existing planner</h2><p>Import this browser’s device-only data into this account. A backup of the current account planner downloads first. The original device data is kept.</p><button class="btn soft" onclick="accountAction('migrate')">Import device planner</button></div>`:''}`:`<p>${s.enabled?'Sign in to save your planner to your private account.':'Cloud accounts are not enabled on this release yet. You can keep planning on this device and export backups.'}</p>`}</div>
 ${s.enabled?`<div class="card" style="margin-top:12px"><h2>${s.user?'Password & security':'Welcome to Vowlo'}</h2><form id="authForm" onsubmit="event.preventDefault();submitAuth(event.submitter?.value||'login')"><div class="field"><label for="authEmail">EMAIL</label><input id="authEmail" type="email" autocomplete="email" ${s.user?'value="'+esc(s.user.email)+'" readonly':''} required></div><div class="field"><label for="authPassword">${s.user?'NEW PASSWORD':'PASSWORD'}</label><input id="authPassword" type="password" autocomplete="${s.user?'new-password':'current-password'}" maxlength="128"><small>Use at least 12 characters for a new password.</small></div><div class="toolbar">${s.user?'<button class="btn" type="submit" value="password">Update password</button>':'<button class="btn" type="submit" value="login">Sign in</button><button class="btn soft" type="submit" value="signup">Create account</button>'}<button class="btn soft" type="button" onclick="submitAuth('reset')">Email password reset</button></div></form><p id="authFeedback" role="status"></p></div>`:''}
 <div class="card" style="margin-top:12px"><h2>Privacy & your device</h2><p>Planner data may contain guests’ contact details and dietary or access needs. Only record what you need and have permission to keep.</p><p>Device-only data stays in this browser. Account data is stored with Supabase and a local copy is kept for offline use. This copy is not separately encrypted; avoid shared devices. Signing out removes this account’s cached planner on this device.</p><p>No advertising or analytics are included. Exported backups contain personal data; keep them private. Deleting cloud data cannot erase copies already exported or cached on other devices. Server backup retention follows the configured hosting plan.</p><div class="toolbar"><button class="btn soft" onclick="exportData()">Export planner</button><button class="btn soft" onclick="VowloCloud.exportLegacy()">Export original device data</button><button class="btn danger" onclick="resetApp()">Delete planner data</button><button class="btn danger" onclick="VowloCloud.eraseDeviceData()">Remove original device data</button></div>${s.user?`<details><summary>Delete account permanently</summary><p>This deletes your sign-in and cloud planner. Other offline devices cannot sync this deleted account.</p><div class="field"><label for="deletePassword">CURRENT PASSWORD</label><input id="deletePassword" type="password" autocomplete="current-password"></div><button class="btn danger" onclick="accountAction('delete')">Delete my account</button></details>`:''}</div>`;
}
render=function(){
 if(page==='account')$('#app').innerHTML=`<main class="shell">${account()}</main>${nav()}<div class="toast" id="toast" role="status"></div>`;
 else oldRender();
 const shell=$('.shell'), s=VowloCloud.status();
 const banner=document.createElement('div');banner.className='syncbar';banner.innerHTML='<span id="syncStatus" role="status"></span><button class="btn soft small" onclick="go(\'account\')">Account</button>';shell.prepend(banner);
 if(!VowloCloud.editable()&&page!=='account'){
  const warning=document.createElement('div');warning.className='notice';warning.textContent=s.message||'Loading your account. Editing is temporarily locked.';shell.prepend(warning);
  shell.querySelectorAll('input,select,textarea,button:not(.syncbar button)').forEach(el=>el.disabled=true);
 }
 document.querySelectorAll('.field label').forEach(label=>{const input=label.parentElement.querySelector('input,select,textarea');if(input?.id)label.htmlFor=input.id;});
 document.querySelectorAll('button').forEach(button=>{if(button.textContent==='×')button.setAttribute('aria-label','Delete record');});
 updateCloudStatus();if(window.vowloWaitingReg?.waiting)showUpdate(window.vowloWaitingReg);
};
function updateCloudStatus(){const s=VowloCloud.status(),text=s.busy?'Syncing…':s.message||'Saved on this device';if($('#syncStatus'))$('#syncStatus').textContent=text;if($('#accountStatus'))$('#accountStatus').textContent=text;
 const marker=!!s.conflict;if(page==='account'&&window.lastConflict!==marker){window.lastConflict=marker;render();}}
function filterGuests(input){window.guestQuery=input.value;const q=input.value.toLowerCase();$('#guestResults').innerHTML=data.guests.map((x,i)=>[x,i]).filter(([x])=>!q||JSON.stringify(x).toLowerCase().includes(q)).map(([x,i])=>guestRow(x,i)).join('')||'<div class="empty">No matching guests.</div>';}
async function submitAuth(action){
 const form=$('#authForm'),email=val('#authEmail'),password=$('#authPassword')?.value||'';
 if(!$('#authEmail').reportValidity())return;
 if(action!=='reset' && !password)return $('#authFeedback').textContent='Enter your password.';
 if(['signup','password'].includes(action)&&password.length<12)return $('#authFeedback').textContent='Use a password of at least 12 characters.';
 form.querySelectorAll('button').forEach(b=>b.disabled=true);
 $('#authFeedback').textContent='Please wait…';
 try{const message=await VowloCloud.auth(action,email,password);if($('#authFeedback'))$('#authFeedback').textContent=message;if($('#authPassword'))$('#authPassword').value='';window.vowloDraft=false;}
 catch(e){if($('#authFeedback'))$('#authFeedback').textContent=e.message||'Something went wrong. Try again.';}
 finally{form.querySelectorAll('button').forEach(b=>b.disabled=false);}
}
async function accountAction(action){try{if(action==='logout')await VowloCloud.logout();if(action==='migrate')await VowloCloud.migrateLocal();if(['remote','local'].includes(action))await VowloCloud.resolve(action);if(action==='delete')await VowloCloud.deleteAccount($('#deletePassword')?.value||'');render();}catch(e){alert(e.message);}}
importData=function(input){const owner=VowloCloud.status().user?.id||null;const f=input.files?.[0];if(!f)return;if(f.size>2000000){input.value='';return alert('Backup exceeds the 2 MB limit.');}const reader=new FileReader();reader.onload=()=>{try{if(owner!==(VowloCloud.status().user?.id||null))throw Error('Account changed. Choose your backup again.');const next=VowloModel.normalize(JSON.parse(reader.result));if(!confirm('Replace the current planner with this backup? Export your current planner first.'))return;data=next;if(save('Backup imported')){render();alert('Backup loaded. Check the sync status if you are signed in.');}}catch(e){alert('Backup not imported: '+e.message);}finally{input.value='';}};reader.onerror=()=>alert('Could not read the backup. Please try again.');reader.readAsText(f);};
resetApp=function(){const cloud=!!VowloCloud.status().user;if(confirm(cloud?'Delete all data in this account’s planner? This deletion syncs when online. Export a backup first.':'Delete this device’s V4 planner? The original V3 recovery copy remains available. Export a backup first.')){data=VowloModel.empty();save('Planner cleared');render();}};
function editRecord(key,index){
 if(!VowloCloud.editable())return;
 const item=data[key][index],fields=schemas[key]?.fields||Object.keys(item).filter(k=>!['done','status'].includes(k)||key!=='tasks').map(k=>[k,k.replace(/([A-Z])/g,' $1')]);
 const dialog=document.createElement('dialog');dialog.className='editor';
 dialog.innerHTML=`<form id="editForm"><h2>Edit ${esc(key==='expenses'?'budget item':key==='tables'?'table':'record')}</h2>${fields.map(([k,label],i)=>{let options=k==='rsvp'?['Awaiting','Yes','No']:k==='table'?['',...data.tables.map(t=>t.name)]:null;let type=['estimate','final','paid','capacity','budget','guestLimit'].includes(k)?'number':k==='due'?'date':k==='email'?'email':'text';return `<div class="field"><label for="edit${i}">${esc(label.toUpperCase())}</label>${options?`<select id="edit${i}">${options.map(x=>`<option value="${esc(x)}" ${item[k]===x?'selected':''}>${esc(x||'Unassigned')}</option>`).join('')}</select>`:`<input id="edit${i}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(item[k]??'')}">`}</div>`;}).join('')}<div class="toolbar"><button class="btn" type="submit">Save changes</button><button class="btn soft" type="button" id="cancelEdit">Cancel</button></div></form>`;
 document.body.append(dialog);dialog.showModal();const close=()=>{window.vowloDraft=false;dialog.close();dialog.remove();};dialog.querySelector('#cancelEdit').onclick=close;dialog.addEventListener('cancel',()=>{window.vowloDraft=false;dialog.remove();});
 dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const updated={...item};fields.forEach(([k],i)=>{const el=dialog.querySelector('#edit'+i);updated[k]=el.type==='number'?(el.value===''&&k==='final'?null:Number(el.value)):el.value.trim();});
 if(!String(updated[fields[0][0]]||'').trim())return alert('Add a name or first field.');
 if(key==='tables'){
  if(!(updated.capacity>0))return alert('Table capacity must be above zero.');
  if(data.tables.some((x,i)=>i!==index&&x.name.toLowerCase()===updated.name.toLowerCase()))return alert('Table name already exists.');
  data.guests.forEach(g=>{if(g.table===item.name)g.table=updated.name;});
 }
 data[key][index]=updated;if(save()){close();render();}};
}
// Fix numerical input validation without replacing original forms.
const originalAddExpense=addExpense;addExpense=function(){if(['#expenseEst','#expenseFinal','#expensePaid'].some(id=>val(id)!==''&&(!Number.isFinite(+val(id))||+val(id)<0)))return alert('Amounts must be zero or greater.');originalAddExpense();};
const originalAddTable=addTable;addTable=function(){if(!Number.isInteger(+val('#tableCap'))||+val('#tableCap')<1)return alert('Use a positive whole number of seats.');originalAddTable();};
const originalSaveSetup=saveSetup;saveSetup=function(){if(+val('#sBudget')<0||+val('#sLimit')<0)return alert('Budget and guest limit cannot be negative.');if(!/^[a-z]{3}$/i.test(val('#sCurrency')))return alert('Use a three-letter currency code, for example USD.');originalSaveSetup();};
document.addEventListener('input',e=>{if(e.target.matches('input,select,textarea')&&!e.target.classList.contains('search'))window.vowloDraft=true;});
window.addEventListener('beforeunload',e=>{if(window.vowloDraft){e.preventDefault();e.returnValue='';}});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{reg.update();if(reg.waiting)showUpdate(reg);reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate(reg);});});}).catch(()=>{const note=document.createElement('p');note.className='notice';note.textContent='Offline installation failed. Keep a backup and retry online.';$('.shell').prepend(note);}));}
function showUpdate(reg){window.vowloWaitingReg=reg;document.querySelector('.update')?.remove();const note=document.createElement('div');note.className='notice update';note.innerHTML='A new version is available. Save or export your work before reloading. <button class="btn soft small">Update app</button>';note.querySelector('button').onclick=()=>{if(window.vowloDraft)return alert('Save or cancel your form first.');navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting?.postMessage({type:'ACTIVATE'});};$('.shell').prepend(note);}
render();void VowloCloud.init();
