const {chromium}=require('playwright');const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve('.'),mime={'.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.html':'text/html'};
const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;const p=path.join(root,pathname==='/'?'index.html':pathname);try{res.setHeader('Content-Type',mime[path.extname(p)]||'text/plain');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end('Not found')}});
async function waitFor(page,fn){const end=Date.now()+15000;while(Date.now()<end){if(await page.evaluate(fn))return;await new Promise(r=>setTimeout(r,25));}throw Error('Timed out: '+fn);}
let count=0;function ok(value,label){assert(value,label);count++;console.log('PASS',label)}
const empty={version:4,setup:{names:'',date:'',budget:0,currency:'USD',guestLimit:0},tasks:[],guests:[]};
(async()=>{await new Promise(r=>server.listen(8087,'127.0.0.1',r));const browser=await chromium.launch({headless:true});const ctx=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});let errors=[];const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
await p.goto('http://127.0.0.1:8087/');ok(await p.locator('.tabs button').count()===5,'Five navigation tabs');
await p.getByRole('button',{name:'Plan',exact:true}).click();await p.locator('#taskName').fill('Book florist');await p.getByRole('button',{name:'Add task',exact:true}).click();ok(await p.locator('.row').count()===1,'Create task');
await p.locator('.row').getByRole('button',{name:'Edit record'}).click();await p.locator('#edit0').fill('Book florist revised');await p.getByRole('button',{name:'Save changes'}).click();ok(await p.locator('.row').innerText().then(t=>t.includes('revised')),'Update task');
await p.locator('.check').check();ok(await p.locator('.pill.done').count()===1,'Complete task');await p.reload();await p.evaluate(()=>go('plan'));ok(await p.locator('.row').count()===1,'Local persistence after reload');
await p.evaluate(()=>go('budget'));await p.locator('#expenseItem').fill('Free flowers');await p.locator('#expenseEst').fill('100');await p.locator('#expenseFinal').fill('0');await p.getByRole('button',{name:'Add budget item'}).click();ok(await p.evaluate(()=>spent())===0,'Final zero is respected');
await p.evaluate(()=>go('seating'));await p.locator('#tableName').fill('Table A');await p.getByRole('button',{name:'Add table',exact:true}).click();
await p.evaluate(()=>go('guests'));await p.locator('#guestName').fill('Alice Example');await p.locator('#guestTable').selectOption('Table A');await p.getByRole('button',{name:'Add guest',exact:true}).click();await p.locator('.search').pressSequentially('Alice');ok(await p.locator('.search').inputValue()==='Alice','Search retains focus through typing');
await p.locator('.row').getByRole('button',{name:'Edit record'}).click();await p.locator('#edit0').fill('Alice Updated');await p.getByRole('button',{name:'Save changes'}).click();ok(await p.locator('.row').innerText().then(t=>t.includes('Updated')),'Update guest');
await p.evaluate(()=>go('seating'));await p.getByRole('button',{name:'Edit',exact:true}).click();await p.locator('#edit0').fill('Family table');await p.getByRole('button',{name:'Save changes'}).click();ok(await p.evaluate(()=>data.guests[0].table)==='Family table','Renaming table preserves guest assignment');
for(const k of ['vendors','timeline','venues','photos','music','honeymoon','emergency','gifts','inspiration','contacts']){await p.evaluate(k=>go(k),k);await p.locator('#f0').fill('Test '+k);await p.getByRole('button',{name:'Add',exact:true}).click();await p.getByRole('button',{name:'Edit',exact:true}).click();await p.locator('#edit0').fill('Updated '+k);await p.getByRole('button',{name:'Save changes'}).click();ok(await p.locator('.row').innerText().then(t=>t.includes('Updated')),'CRUD screen '+k);await p.getByRole('button',{name:'Delete record'}).click();ok(await p.locator('.row').count()===0,'Delete '+k);}
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});for(const page of ['home','plan','guests','budget','more','account']){await p.evaluate(k=>go(k),page);ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No horizontal overflow ${width}/${page}`);}}
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>go('home'));await p.screenshot({path:'tests/mobile-home.png',fullPage:true});
await p.evaluate(()=>go('more'));const download=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Export backup'}).click()]);const backup=JSON.parse(fs.readFileSync(await download[0].path(),'utf8'));ok(backup.tasks[0].name==='Book florist revised','Export contains actual planner');
await p.locator('#importFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...empty,setup:{...empty.setup,names:'Restored'}}))});await waitFor(p,()=>data.setup.names==='Restored');ok(true,'Import valid backup');
await p.locator('#importFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"setup":{},"tasks":"bad"}')});ok(await p.evaluate(()=>data.setup.names)==='Restored','Invalid import preserves data');
await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await ctx.setOffline(true);await p.reload();ok(await p.locator('.brand').textContent()==='VOWLO','PWA shell loads offline');await ctx.setOffline(false);
const legacy=await browser.newContext();const lp=await legacy.newPage();await lp.addInitScript(value=>{if(!localStorage.getItem('vowloData'))localStorage.setItem('vowloData',JSON.stringify(value));},{...empty,version:3,setup:{...empty.setup,names:'Legacy Couple'},tasks:[['Old task','Planning',true]]});await lp.goto('http://127.0.0.1:8087/');ok(await lp.evaluate(()=>data.tasks[0].done),'Legacy array migration');ok(await lp.evaluate(()=>JSON.parse(localStorage.getItem('vowloData')).version)===3,'Original V3 stays untouched');await legacy.close();
// Real Supabase SDK with mocked HTTP responses. This tests frontend, not hosted auth/RLS.
const records=new Map(),users=new Map(),tokens=new Map();let offlineAPI=false;
function makeSession(email){let u=users.get(email);if(!u){u={id:email.startsWith('a')?'11111111-1111-4111-8111-111111111111':'22222222-2222-4222-8222-222222222222',email,aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:new Date().toISOString()};users.set(email,u);}const token=['e30',Buffer.from(JSON.stringify({sub:u.id,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'signature'].join('.');tokens.set(token,u);return {access_token:token,refresh_token:'refresh-'+u.id,expires_in:3600,token_type:'bearer',user:u};}
async function cloudPage(){const c=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});await c.route('**/config.js*',route=>route.fulfill({contentType:'application/javascript',body:"window.VOWLO_CONFIG={supabaseUrl:'https://testproj.supabase.co',supabaseKey:'sb_publishable_test',cloudEnabled:true}"}));await c.route('https://testproj.supabase.co/**',async route=>{if(offlineAPI)return route.abort();const req=route.request(),url=new URL(req.url()),u=tokens.get((req.headers().authorization||'').replace('Bearer ',''));let body={};if(req.postData())try{body=JSON.parse(req.postData())}catch{}let result={},status=200;
if(url.pathname==='/auth/v1/token')result=makeSession(body.email||'a@example.com');else if(url.pathname==='/auth/v1/user')result=u||{};else if(url.pathname==='/auth/v1/logout')result={};else if(url.pathname==='/auth/v1/recover')result={};else if(url.pathname==='/auth/v1/signup')result={user:makeSession(body.email).user,session:null};else if(!u){status=401;result={message:'Unauthorized'};}else if(url.pathname==='/rest/v1/weddings')result=records.get(u.id)||null;else if(url.pathname==='/rest/v1/rpc/save_wedding'){const current=records.get(u.id);if((current?.revision||0)!==body.p_expected_revision)result=[];else{const row={user_id:u.id,payload:body.p_payload,revision:(current?.revision||0)+1,updated_at:new Date().toISOString()};records.set(u.id,row);result=[row];}}else if(url.pathname==='/rest/v1/rpc/delete_my_account'){records.delete(u.id);result=null;}else {status=404;result={message:'Unknown endpoint '+url.pathname};}
await route.fulfill({status,contentType:'application/json',body:JSON.stringify(result)});});const page=await c.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:8087/');return [c,page];}
async function login(page,email){await page.evaluate(()=>go('account'));await page.locator('#authEmail').fill(email);await page.locator('#authPassword').fill('strong-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await waitFor(page,()=>VowloCloud.status().ready&&!VowloCloud.status().busy);}
const [ca,a]=await cloudPage();await login(a,'a@example.com');ok(await a.evaluate(()=>data.tasks.length)===0,'New account starts empty');await a.evaluate(()=>go('plan'));await a.locator('#taskName').fill('Cloud A task');await a.getByRole('button',{name:'Add task'}).click();await waitFor(a,()=>!VowloCloud.status().dirty&&!VowloCloud.status().busy);ok(records.values().next().value.payload.tasks[0].name==='Cloud A task','Cloud save reaches backend');
const [cb,b]=await cloudPage();await login(b,'a@example.com');ok(await b.evaluate(()=>data.tasks[0].name)==='Cloud A task','Second device pulls account data');
await cb.setOffline(true);await b.evaluate(()=>go('plan'));await b.locator('#taskName').fill('Offline B edit');await b.getByRole('button',{name:'Add task'}).click();ok(await b.evaluate(()=>VowloCloud.status().dirty),'Offline change stays pending');
await a.locator('#taskName').fill('New A edit');await a.getByRole('button',{name:'Add task'}).click();await waitFor(a,()=>!VowloCloud.status().dirty&&!VowloCloud.status().busy);await cb.setOffline(false);await b.evaluate(()=>VowloCloud.sync());await waitFor(b,()=>VowloCloud.status().conflict);ok(await b.evaluate(()=>data.tasks.some(x=>x.name==='Offline B edit')),'Conflict preserves local copy');ok(records.values().next().value.payload.tasks.some(x=>x.name==='New A edit'),'Conflict preserves cloud copy');await b.evaluate(()=>VowloCloud.resolve('remote'));ok(await b.evaluate(()=>data.tasks.some(x=>x.name==='New A edit')),'Explicit cloud resolution');
await b.evaluate(()=>VowloCloud.logout());await login(b,'b@example.com');ok(await b.evaluate(()=>data.tasks.length)===0,'Account B never displays account A data');
await a.evaluate(()=>{localStorage.setItem('vowloData',JSON.stringify({...VowloModel.empty(),version:3,setup:{...VowloModel.empty().setup,names:'Migrated Couple'}}));});await a.evaluate(()=>VowloCloud.migrateLocal());await waitFor(a,()=>!VowloCloud.status().busy&&!VowloCloud.status().dirty);ok(await a.evaluate(()=>data.setup.names)==='Migrated Couple','V3 explicit migration to account');ok(await a.evaluate(()=>JSON.parse(localStorage.getItem('vowloData')).version)===3,'Migration leaves V3 source intact');
await a.evaluate(()=>resetApp());await waitFor(a,()=>!VowloCloud.status().busy&&!VowloCloud.status().dirty);ok(records.get('11111111-1111-4111-8111-111111111111').payload.setup.names==='','Cloud deletion stores revisioned empty planner');
await a.evaluate(()=>VowloCloud.deleteAccount('strong-password-123'));ok(!records.has('11111111-1111-4111-8111-111111111111'),'Account deletion RPC invoked');
ok(errors.length===0,'No JavaScript runtime errors: '+errors.join('; '));await ca.close();await cb.close();await ctx.close();await browser.close();server.close();console.log(`${count} browser checks passed.`);
})().catch(e=>{console.error(e);server.close();process.exit(1)});
