const {PGlite}=require('@electric-sql/pglite');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const db=new PGlite();let count=0;
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
await db.exec(fs.readFileSync('supabase/migrations/202610040001_vowlo.sql','utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
await db.exec(`insert into auth.users values('${a}'),('${b}');`);
const as=async(id,role='authenticated')=>db.exec(`reset role;set role ${role};set request.jwt.claim.sub='${id}';`);
const ok=(value,label)=>{assert(value,label);count++;console.log('PASS',label)};
const denied=async(sql,label)=>{let failed=false;try{await db.exec(sql)}catch{failed=true}ok(failed,label)};
await as(a);let r=await db.query(`select * from public.save_wedding('{"owner":"A"}',0)`);ok(r.rows[0].user_id===a,'A creates own planner');
await as(b);ok((await db.query('select * from public.weddings')).rows.length===0,'B cannot read A');
ok((await db.query(`update public.weddings set payload='{}' where user_id='${a}' returning *`)).rows.length===0,'B cannot update A');
await denied(`insert into public.weddings(user_id,payload) values('${a}','{}')`,'B cannot insert for A');
await db.query(`select * from public.save_wedding('{"owner":"B"}',0)`);
await denied(`update public.weddings set user_id='${a}' where user_id='${b}'`,'B cannot transfer ownership');
await as(a);r=await db.query(`select * from public.save_wedding('{"owner":"A2"}',1)`);ok(r.rows[0].revision===2,'Revision increment');
ok((await db.query(`select * from public.save_wedding('{"stale":true}',1)`)).rows.length===0,'Stale revision cannot overwrite');
ok((await db.query(`select * from public.save_wedding('{}',0)`)).rows.length===0,'Duplicate first write cannot overwrite');
await denied(`delete from public.weddings`,'Direct delete denied');
await as('', 'anon');await denied('select * from public.weddings','Anonymous read denied');await denied(`select * from public.save_wedding('{}',0)`,'Anonymous write denied');await denied('select public.delete_my_account()','Anonymous account delete denied');
await as(a);await db.query('select public.delete_my_account()');
await db.exec('reset role');ok((await db.query(`select * from auth.users where id='${a}'`)).rows.length===0,'Self account deletion');ok((await db.query(`select * from public.weddings where user_id='${a}'`)).rows.length===0,'Cascade removes planner');ok((await db.query(`select * from public.weddings where user_id='${b}'`)).rows.length===1,'Other account preserved');
await as(a);await denied(`select * from public.save_wedding('{}',0)`,'Deleted token cannot recreate planner');
console.log(`${count} SQL/RLS checks passed (local PostgreSQL; hosted verification pending).`);await db.close();})().catch(e=>{console.error(e);process.exit(1)});
